In [219]:
# feature selection is a technique in which we select columns from the data that a important and also
# figure out and remove those which are less important than others for data sciencee and ML
# there are two types, forward and backward eleminaion to train model with highest accuracy
import pandas as pd
from mlxtend.feature_selection import SequentialFeatureSelector
dataset=pd.read_csv(r"ONEHOTENCOE.csv")
dataset

     ProductID   Color Size  Gender        Brand   Price  Rating InStock
0         1001    Blue   XL  Unisex       Adidas  135.79     4.2    True
1         1002   White   XL  Unisex         Puma  118.57     3.5    True
2         1003  Yellow    M  Unisex       Adidas  160.36     5.0    True
3         1004   Green    S  Female         Puma   58.14     4.5    True
4         1005     Red    S    Male  New Balance  115.53     3.4    True
..         ...     ...  ...     ...          ...     ...     ...     ...
111       1112     Red    L  Unisex  New Balance   92.12     5.0    True
112       1113   White    L  Female         Nike   58.53     4.4    True
113       1114   Black    M    Male  New Balance   35.22     5.0    True
114       1115  Yellow    S    Male         Puma   62.37     3.6    True
115       1116   Black    L  Female          NaN     NaN     NaN     NaN

[116 rows x 8 columns]

In [220]:
dataset.shape

(116, 8)

In [221]:
dataset.isnull().sum()

ProductID    0
Color        0
Size         0
Gender       0
Brand        1
Price        1
Rating       1
InStock      1
dtype: int64

In [222]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ProductID  116 non-null    int64
 1   Color      116 non-null    object
 2   Size       116 non-null    object
 3   Gender     116 non-null    object
 4   Brand      115 non-null    object
 5   Price      115 non-null    float64
 6   Rating     115 non-null    float64
 7   InStock    115 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 7.4+ KB

In [223]:
num=dataset.select_dtypes(include=['int64','float64']).columns
dataset[num]=dataset[num].fillna(dataset[num].median())

In [224]:
cat_data=dataset.select_dtypes(include=['object']).columns
dataset[cat_data]=dataset[cat_data].fillna(dataset[cat_data].mode().iloc[0])

C:\Users\dell\AppData\Local\Temp\ipykernel_8488\2440375014.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset[cat_data]=dataset[cat_data].fillna(dataset[cat_data].mode().iloc[0])

In [225]:
dataset

     ProductID   Color Size  Gender        Brand   Price  Rating  InStock
0         1001    Blue   XL  Unisex       Adidas  135.79     4.2     True
1         1002   White   XL  Unisex         Puma  118.57     3.5     True
2         1003  Yellow    M  Unisex       Adidas  160.36     5.0     True
3         1004   Green    S  Female         Puma   58.14     4.5     True
4         1005     Red    S    Male  New Balance  115.53     3.4     True
..         ...     ...  ...     ...          ...     ...     ...      ...
111       1112     Red    L  Unisex  New Balance   92.12     5.0     True
112       1113   White    L  Female         Nike   58.53     4.4     True
113       1114   Black    M    Male  New Balance   35.22     5.0     True
114       1115  Yellow    S    Male         Puma   62.37     3.6     True
115       1116   Black    L  Female         Nike   82.81     4.1     True

[116 rows x 8 columns]

In [226]:
# one hot encoding
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,ProductID,Price,Rating,InStock,Color_Blue,Color_Green,Color_Red,Color_White,Color_Yellow,Size_M,Size_S,Size_XL,Size_XS,Size_XXL,Gender_Male,Gender_Unisex,Brand_New Balance,Brand_Nike,Brand_Puma,Brand_Under Armour
0,1001,135.79,4.2,True,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False
1,1002,118.57,3.5,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True,False
2,1003,160.36,5.0,True,False,False,False,False,True,True,False,False,False,False,False,True,False,False,False,False
3,1004,58.14,4.5,True,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False
4,1005,115.53,3.4,True,False,False,True,False,False,False,True,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,1112,92.12,5.0,True,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False
112,1113,58.53,4.4,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False
113,1114,35.22,5.0,True,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False
114,1115,62.37,3.6,True,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False
115,1116,82.81,4.1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [227]:
# from sklearn.preprocessing import OneHotEncoder
# OHE=OneHotEncoder()
# EN=OHE.fit_transform(dataset).toarray()
# EN

In [228]:
# pd.DataFrame(EN,dataset)

In [229]:
x=dataset.iloc[:,:-1] #iloc is integers location
y=dataset["Rating"]

now we need to make a model

In [230]:
x.shape

(116, 19)

In [231]:
x.isnull().sum()

ProductID            0
Price                0
Rating               0
InStock              0
Color_Blue           0
Color_Green          0
Color_Red            0
Color_White          0
Color_Yellow         0
Size_M               0
Size_S               0
Size_XL              0
Size_XS              0
Size_XXL             0
Gender_Male          0
Gender_Unisex        0
Brand_New Balance    0
Brand_Nike           0
Brand_Puma           0
dtype: int64

In [232]:
x.isnull().sum()

ProductID            0
Price                0
Rating               0
InStock              0
Color_Blue           0
Color_Green          0
Color_Red            0
Color_White          0
Color_Yellow         0
Size_M               0
Size_S               0
Size_XL              0
Size_XS              0
Size_XXL             0
Gender_Male          0
Gender_Unisex        0
Brand_New Balance    0
Brand_Nike           0
Brand_Puma           0
dtype: int64

In [233]:
x.shape

(116, 19)

In [234]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
FS=SequentialFeatureSelector(lr, k_features=2, forward=True)
FS.fit(x,y)

SequentialFeatureSelector(estimator=LinearRegression(), k_features=(2, 2),
                          scoring='r2')

In [235]:
FS.feature_names

['ProductID',
 'Price',
 'Rating',
 'InStock',
 'Color_Blue',
 'Color_Green',
 'Color_Red',
 'Color_White',
 'Color_Yellow',
 'Size_M',
 'Size_S',
 'Size_XL',
 'Size_XS',
 'Size_XXL',
 'Gender_Male',
 'Gender_Unisex',
 'Brand_New Balance',
 'Brand_Nike',
 'Brand_Puma']

In [236]:
FS.k_score_

np.float64(1.0)